# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='who',
            old_name='user',
            new_name='usr_id',
        ),
    ]
